### ISSUE TITLE
Lesson plan submission should fail with error when submitting with title that already exists

### ISSUE THREAD

**Issue by chriskei** [lukesanantonio/firstbyte#51]
The submission currently fails, we need to add properly error handling.

**Comment by zacharyjarnagin** [comment]
Checkout branch `display_title_error`! It now throws an error labeled "object [object]"! We need to change this and the scroll up effect needs to be fixed.

**Comment by zacharyjarnagin** [comment]
So new issues. The errors are now being displayed! But...

1. The error does not display on the first click of the submit button (it has to be hit at least twice)
2. The window does not scroll up far enough to display the field as it is hidden by the navbar. The 
    error clips through the navbar.
3. When a field that originally had an error is changed, clicking submit still displays the same error.

e
